add activity report
PrivacyLx/website pull request #61
Opened 2021-01-23 21:30 UTC by francisco-core

2021-01-26 19:50 UTC, anadahz requested changes
@francisco-core Thank you very much for this PR.

Please, add the missing file and keep the case of the items in the list consistent.

2021-01-26 19:50 UTC, anadahz commented on content/about/about-us.en.md
> +* [Activity report 2018-2020](/documents/activities/relatorio-atividades-2020.pdf) (in Portuguese)
The file in `/documents/activities/relatorio-atividades-2020.pdf` doesn't exist.

Minor: `Activity report` should be `Activity Report` or all other items in the list should be in lowercase.

2021-01-26 19:50 UTC, anadahz commented on content/about/about-us.pt.md
> +* [Relatório de Atividades 2018-2020](/documents/activities/relatorio-atividades-2020.pdf)
Same as in the English version.
The file in `/documents/activities/relatorio-atividades-2020.pdf` doesn't exist.

2021-01-27 17:28 UTC, francisco-core commented on content/about/about-us.pt.md
> +* [Relatório de Atividades 2018-2020](/documents/activities/relatorio-atividades-2020.pdf)
Well spotted. Just uploaded it. Please check again.

2021-01-27 17:29 UTC, francisco-core commented on content/about/about-us.en.md
> +* [Activity report 2018-2020](/documents/activities/relatorio-atividades-2020.pdf) (in Portuguese)
fixed

2021-01-27 19:25 UTC, francisco-core commented
Both addressed @anadahz. Merging.

2021-01-27 19:25 UTC, merged

2021-01-28 14:17 UTC, anadahz commented
Thanks @francisco-core .